# Generated by Django 4.1.5 on 2023-03-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_remove_users_id_alter_users_nid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
