# Generated by Django 4.1.5 on 2023-03-12 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0004_rename_users_user_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phone', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('post_code', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
