# Generated by Django 4.1.5 on 2023-03-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_train'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='train',
            table='train',
        ),
    ]
