# Generated by Django 4.1.5 on 2023-03-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_train_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='tr_arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='tr_departure',
            field=models.TimeField(),
        ),
    ]
