# Generated by Django 4.1.3 on 2023-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_rename_bio_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
