# Generated by Django 4.1.5 on 2023-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_users_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='nid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
