# Generated by Django 4.1.5 on 2023-03-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_name', models.CharField(max_length=100)),
                ('tr_source', models.CharField(max_length=100)),
                ('tr_destination', models.CharField(max_length=100)),
                ('tr_departure', models.DateField()),
                ('tr_arrival', models.DateField()),
                ('tr_total_seat', models.IntegerField()),
            ],
        ),
    ]
