# Generated by Django 4.1.5 on 2023-03-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_alter_train_tr_arrival_alter_train_tr_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('serial_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stops_name', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.train')),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
