# Generated by Django 4.1.5 on 2023-03-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_rename_tr_total_seat_train_tr_total_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='serial_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
