# Generated by Django 4.1.5 on 2023-03-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_profile_bio_alter_route_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='address',
        ),
    ]
