# Generated by Django 4.1.7 on 2023-03-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_booking_alter_profile_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
