# Generated by Django 4.1.7 on 2023-03-15 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0017_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_constraint',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='train_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('seat_number', 'booking_date'), name='unique_booking_constraint'),
        ),
    ]
