# Generated by Django 4.1.7 on 2023-03-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0021_alter_booking_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_id',
            field=models.IntegerField(null=True),
        ),
    ]
