# Generated by Django 4.1.7 on 2023-03-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0022_booking_from_id_booking_to_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_id',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.train')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
    ]
