# Generated by Django 4.1.7 on 2023-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_remove_booking_from_id_remove_booking_to_id_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket_cost',
            },
        ),
    ]
