# Generated by Django 4.1.7 on 2023-03-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_ticketcost'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticketcost',
            table='ticketcost',
        ),
    ]
