# Generated by Django 4.1.7 on 2023-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0025_alter_ticketcost_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=100)),
                ('dst', models.CharField(max_length=100)),
                ('cst', models.IntegerField()),
                ('route', models.ManyToManyField(to='features.route')),
            ],
        ),
    ]
