# Generated by Django 4.1.7 on 2023-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0026_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
